version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=294250817254.dkr.ecr.us-east-1.amazonaws.com/notification-service
      - VERSION=$((date +%F+%T) | tr + T)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$VERSION
      - docker push $REPOSITORY_URI:$VERSION
      - docker push $REPOSITORY_URI:latest
